language: python

matrix:
    include:
        - os: osx
          language: generic
          env: TOXENV=py33

script:
  - python3 --version
  - git clone https://github.com/vinay0410/cpython.git
  - cd cpython
  - git checkout fix-fcntl
  - ./configure --with-pydebug && make -j2
  - echo "abcd" >> file.txt
  - ./python.exe ../test.py